#!/usr/bin/env bash

config() {
    TEMPLATE=
    while getopts "t:" opt $@; do
      case $opt in
        t)
            TEMPLATE=$OPTARG
            ;;
        [?])
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
      esac
    done

    if [ -z $TEMPLATE ]; then
        echo "$0: missing template!"
        usage
    fi

    GIT="git"
    which hub &> /dev/null
    if [ $? -eq 0 ]; then
        GIT="hub"
    fi
}

usage() {
    echo "TODO. Sorry!"
    exit 1
}

build() {
    BUILDDIR=$(mktemp -d -t typewriter)
    if [ $? -ne 0 ]; then
        echo "$0: can't create temporary build directory!"
        exit 1
    fi
    echo "$0: building in $BUILDDIR..."
    
    $GIT clone $TEMPLATE $BUILDDIR &> /dev/null

    (cd $BUILDDIR && make clean &> /dev/null)
    cp README* $BUILDDIR/src
    (cd $BUILDDIR && make build &> /dev/null)
    if [ $? -ne 0 ]; then
        echo "$0: build failed!"
        exit 1
    fi

    touch $BUILDDIR/build/.typewriter
    touch $BUILDDIR/build/.nojekyll

    echo "$0: build finished"
}

prepare() {
    $GIT update-index --ignore-submodules --refresh &> /dev/null
    if [ $? -ne 0 ]; then
        echo "$0: git repository not clean!"
        exit 1
    fi

    $GIT pull origin gh-pages &> /dev/null
    if [ $? -eq 0 ]; then
        existingBranch
    else
        newBranch
    fi

    echo "$0: gh-pages branch prepared"
}

existingBranch() {
    $GIT checkout gh-pages &> /dev/null
    if [ ! -f .typewriter ]; then
        echo "$0: gh-pages branch exists, but was not built by typewriter!"
        exit 1
    fi
    $GIT ls-files -z | xargs -0 rm -f &> /dev/null
}

newBranch() {
    $GIT symbolic-ref HEAD refs/heads/gh-pages &> /dev/null
    rm .git/index
    $GIT clean -fdx &> /dev/null
}

commit() {
    cp -R $BUILDDIR/build/ .

    $GIT add -A &> /dev/null
    $GIT commit -m "typewriter build $(date -u +%Y-%m-%dT%H:%MZ)" &> /dev/null
    echo "$0: copied and committed build"

    $GIT push origin gh-pages &> /dev/null
    echo "$0: pushed to github"

    $GIT checkout master &> /dev/null
}

config $@
build
prepare
commit

trap 'rm -rf $BUILDDIR' EXIT
